export const events = [
  "Pencil Sketch",
  "Photography",
  "Bridal Makeup",
  "Mehendi",
  "Chill Chef",
  "Freeze Dance",
  "Wealth Out of Waste",
  "Reels Challenge",
  "Solo Song",
  "Solo Dance",
  "Group Dance",
  "Instrumental Music",
  "Mime",
  "Group Song",
  "Variety Performance",
  "Fashion Parade",
  "Mr. & Ms. Avatar",
];