export const events = [
  "Solo Song",
  "Solo Dance",
  "Group Dance",
  "Instrumental Music",
  "Mime",
  "Mono Act",
  "Fashion Parade",
  "Mr. & Ms. Fest",
  "Pencil Sketching",
  "Photography",
  "Bridal Makeup",
  "Mehendi",
  "Chill Chef",
  "RJ Hunt",
  "Street Play",
  "Wealth Out of Waste",
  "Technical Quiz",
  "Web Design",
  "Coding Challenge",
  "Hackathon",
  "Ideathon",
  "Digital Designing",
  "Drone Challenge",
  "Best Manager",
  "Commerce Dumb Charades",
  "Vyaapaar Vision",
  "Brand Blitz",
  "Logo Designing",
  "Ad Zap",
  "IPL Auction",
  "Meme Creation",
  "Reels Challenge",
  "Rapid Fire",
  "Freeze Dance",
  "Guess the Song",
];